# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171013_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
